apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Internal Docker network URL
    isDefault: true
    orgId: 1
    editable: true
