global:
  scrape_interval: 15s
  evaluation_interval: 15s

# alerting: # Optional Alertmanager config
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'nestjs-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:3000'] 